title: Genomic surveillance of <i>Anopheles</i> mosquitoes
author: PAMCA and MalariaGEN
copyright: "2022"
execute:
  execute_notebooks: "off"
repository:
  url: https://github.com/anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io
  path_to_book: docs
  branch: master
launch_buttons:
  notebook_interface: "jupyterlab"
  colab_url: "https://colab.research.google.com"
  binderhub_url: ""  # support colab only
html:
  use_repository_button : true
  use_issues_button: true
  extra_footer: |
    <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons Licence" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a> This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
sphinx:
  config:
    myst_enable_extensions:
    - substitution
    - dollarmath
    - colon_fence
