title: Training course in data analysis for genomic surveillance of African malaria vectors
author: MalariaGEN and PAMCA
copyright: "2022"
only_build_toc_files: true
execute:
  # N.B., execution is needed to get some notebooks to render properly,
  # e.g., notebooks using ipyleaflet to create maps. If there are some
  # notebooks which take too long to run, they can be excluded from 
  # execution. See https://jupyterbook.org/content/execute.html#exclude-files-from-execution
  # for configuration syntax.
  execute_notebooks: "auto"
  timeout: 100
  allow_errors: false
  exclude_patterns:
    - 'workshop-1/module-1*'
    # need to execute module 2 as ipyleaflet maps don't render otherwise
    - 'workshop-1/module-3*'
    - 'workshop-1/module-4*'
repository:
  url: https://github.com/anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io
  path_to_book: docs
  branch: master
launch_buttons:
  notebook_interface: "jupyterlab"
  colab_url: "https://colab.research.google.com"
  binderhub_url: ""  # disable binderhub, support colab only
html:
  use_repository_button : true
  use_issues_button: true
  extra_footer: |
    <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons Licence" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a> This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
sphinx:
  config:
    myst_enable_extensions:
    - substitution
    - dollarmath
    - colon_fence
